/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import lapr.project.controller.AssignStandToApplicationController;
import lapr.project.model.Application;
import lapr.project.model.ApplicationList;
import lapr.project.model.EventCenter;
import lapr.project.model.EventRegistry;
import lapr.project.model.Event;
import lapr.project.model.Organizer;
import lapr.project.model.Stand;

/**
 *
 * @author Miguel Santos <1161386@isep.ipp.pt>
 */
public class AssignStandToApplicationUI extends javax.swing.JFrame {

    private static final long serialVersionUID = 1;
    private AssignStandToApplicationController controller;
    private EventRegistry listEvents;
    private String logedUser;
    private DefaultListModel<Stand> modelStandsList = new DefaultListModel<>();
    private Event event;
    private Application app;
    private ApplicationList listApplications;

    /**
     * Creates new form AssignStandToApplicationUI
     *
     * @param eventCenter
     * @param logedUser
     */
    public AssignStandToApplicationUI(EventCenter eventCenter, String logedUser) {
        controller = new AssignStandToApplicationController(eventCenter);
        this.logedUser = logedUser;
        initComponents();

        standJList.setModel(modelStandsList);

        listEvents = controller.getEventsList();
        fillEventComboBox();
        fillApplicationComboBox();

        setVisible(true);
    }

    private void fillEventComboBox() {
        for (int i = 0; i < listEvents.size(); i++) {
            Event e = listEvents.getEvent(i);
            for (int j = 0; j < e.getOrganizerList().size(); j++) {
                Organizer o = e.getOrganizerList().getOrganizer(j);
                if (o.getOrganizer().getUserName().equals(logedUser)) {
                    eventComboBox.addItem(e);
                }
            }
        }
    }

    private void fillApplicationComboBox() {
        listApplications = event.getApplicationsList();
        for (int i = 0; i < listApplications.size(); i++) {
            Application a = listApplications.getApplication(i);
            if (a.getStand() == null) {
                applicationComboBox.addItem(a);
            }
        }
        app = (Application) applicationComboBox.getSelectedItem();
        pretendedStandAreaLabel.setText(String.valueOf(app.getArea()));
    }

    private void fillStandJList() {
        for (int i = 0; i < event.getStandRegister().size(); i++) {
            Stand s = event.getStandRegister().getStand(i);
            modelStandsList.addElement(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        eventComboBox = new javax.swing.JComboBox<Event>();
        jLabel2 = new javax.swing.JLabel();
        applicationComboBox = new javax.swing.JComboBox<Application>();
        jScrollPane1 = new javax.swing.JScrollPane();
        standJList = new javax.swing.JList<Stand>();
        jLabel3 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        assignStandBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pretendedStandAreaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Event:");

        eventComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Application:");

        applicationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicationComboBoxActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(standJList);

        jLabel3.setText("Stand List:");

        cancelBtn.setText("Close");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        assignStandBtn.setText("Assign Stand");
        assignStandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignStandBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Pretended Stand Area:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(applicationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(assignStandBtn)
                                .addGap(18, 18, 18)
                                .addComponent(cancelBtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(pretendedStandAreaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eventComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(applicationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pretendedStandAreaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(assignStandBtn))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void assignStandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignStandBtnActionPerformed
        Stand s = modelStandsList.getElementAt(standJList.getSelectedIndex());
        Application a = (Application) applicationComboBox.getSelectedItem();
        a.setStand(s);
        for (int i = 0; i < event.getStandRegister().size(); i++) {
            Stand s2 = event.getStandRegister().getStand(i);
            if (s2.equals(s)) {
                event.getStandRegister().removeStand(s2);
            }
        }
        JOptionPane.showMessageDialog(null, "Stand assigned with success!");

        applicationComboBox.removeItem(a);
        modelStandsList.removeElement(s);

    }//GEN-LAST:event_assignStandBtnActionPerformed

    
    private void updatePretendedAreaLabel(){
        
    }
    private void applicationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicationComboBoxActionPerformed
        
        if(applicationComboBox.getSelectedItem() != null){
            Application a =(Application) applicationComboBox.getSelectedItem();
            pretendedStandAreaLabel.setText(String.valueOf(a.getArea()));
        }else{
            pretendedStandAreaLabel.setText("");
        }
        


    }//GEN-LAST:event_applicationComboBoxActionPerformed

    private void eventComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventComboBoxActionPerformed

        event = (Event) eventComboBox.getSelectedItem();

        if (eventComboBox.getSelectedItem().toString().equals(event.toString())) {
            modelStandsList.removeAllElements();
            applicationComboBox.removeAllItems();
            fillStandJList();
            if (event.getApplicationsList().size() == 0) {
                JOptionPane.showMessageDialog(null, "Selected event doesn't have applications without stands");
            } else {
                fillApplicationComboBox();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Already Selected");
        }


    }//GEN-LAST:event_eventComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Application> applicationComboBox;
    private javax.swing.JButton assignStandBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<Event> eventComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pretendedStandAreaLabel;
    private javax.swing.JList<Stand> standJList;
    // End of variables declaration//GEN-END:variables
}
