/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javafx.collections.ObservableList;
import javafx.scene.control.ComboBox;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import lapr.project.controller.CreateEventController;
import lapr.project.model.Congress;
import lapr.project.model.EventCenter;
import lapr.project.model.EventRegistry;
import lapr.project.model.Exhibition;
import lapr.project.model.LocationList;
import lapr.project.model.Location;
import lapr.project.model.Organizer;
import lapr.project.model.OrganizersList;
import lapr.project.model.StandRegistry;
import lapr.project.model.User;
import lapr.project.model.UserRegistry;

/**
 *
 * @author MarioDias
 */
public class CreateEvent extends javax.swing.JFrame {

    private static final long serialVersionUID = 1;
    private EventCenter eventCenter;
    private CreateEventController controller;
    private DefaultListModel<User> modelUsersList = new DefaultListModel<User>();
    private DefaultListModel<Organizer> modelOrganizerListEvent = new DefaultListModel<Organizer>();
    private UserRegistry listUsers;
    private OrganizersList listOrganizers;
    private EventRegistry listEvents;
    private LocationList locationList;

    /**
     * Creates new form CreateEvent
     *
     * @param eventCenter
     */
    public CreateEvent(EventCenter eventCenter) {
        this.eventCenter = eventCenter;
        controller = new CreateEventController(this.eventCenter);
        initComponents();
        listEvents = controller.getEventsList();
        locationList = controller.getLocationList();

        listUsers = controller.getUsersList();
        usersJList.setModel(modelUsersList);

        listOrganizers = new OrganizersList();
        organizersList.setModel(modelOrganizerListEvent);

        initObjects();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextField = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        locationCombobox = new javax.swing.JComboBox<Location>();
        newAddressbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        eventBeginningSpinner = new javax.swing.JSpinner();
        eventEndSpinner = new javax.swing.JSpinner();
        SubmitAppStart = new javax.swing.JSpinner();
        submitAppEnd = new javax.swing.JSpinner();
        congressRadiobtn = new javax.swing.JRadioButton();
        exhibitionRadiobtn = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        organizersList = new javax.swing.JList<Organizer>();
        removeOrganizerbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        usersJList = new javax.swing.JList<User>();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addOrganizerbtn = new javax.swing.JButton();
        newEventbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        addOrganizerByIDTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        invitationTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Event");
        setResizable(false);

        jPanel1.setToolTipText("");

        descriptionTextField.setColumns(20);
        descriptionTextField.setRows(5);
        descriptionTextField.setWrapStyleWord(true);
        descriptionTextField.setPreferredSize(new java.awt.Dimension(180, 94));
        jScrollPane1.setViewportView(descriptionTextField);

        jLabel1.setText("Event name:");

        jLabel2.setText("Event starts:");

        jLabel3.setText("Event Ends:");

        jLabel4.setText("Address:");

        jLabel6.setText("Description:");

        locationCombobox.setMinimumSize(new java.awt.Dimension(180, 20));
        locationCombobox.setPreferredSize(new java.awt.Dimension(180, 20));
        locationCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationComboboxActionPerformed(evt);
            }
        });

        newAddressbtn.setText("Create new Address");

        jLabel7.setText("Submission Application starts:");

        jLabel8.setText("Submission Application ends:");

        eventBeginningSpinner.setModel(new javax.swing.SpinnerDateModel());

        eventEndSpinner.setModel(new javax.swing.SpinnerDateModel());

        SubmitAppStart.setModel(new javax.swing.SpinnerDateModel());

        submitAppEnd.setModel(new javax.swing.SpinnerDateModel());

        congressRadiobtn.setText("Congress");
        congressRadiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congressRadiobtnActionPerformed(evt);
            }
        });

        exhibitionRadiobtn.setText("Exhibiton");
        exhibitionRadiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exhibitionRadiobtnActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(organizersList);

        removeOrganizerbtn.setText("Remove Organizer");
        removeOrganizerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeOrganizerbtnActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(usersJList);

        jLabel9.setText("Event's Organizers");

        jLabel5.setText("Users List");

        addOrganizerbtn.setText("Add Organizer From List");
        addOrganizerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrganizerbtnActionPerformed(evt);
            }
        });

        newEventbtn.setText("New Event");
        newEventbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEventbtnActionPerformed(evt);
            }
        });

        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Add Organizer By ID:");

        addOrganizerByIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrganizerByIDTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Number of invitations:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel11)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(congressRadiobtn)
                                .addGap(40, 40, 40)
                                .addComponent(exhibitionRadiobtn)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(locationCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(newAddressbtn))
                                            .addComponent(invitationTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SubmitAppStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(submitAppEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eventEndSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eventBeginningSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 42, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(224, 224, 224)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addOrganizerByIDTextField))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addOrganizerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(newEventbtn)
                                .addGap(18, 18, 18)
                                .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                .addComponent(removeOrganizerbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventBeginningSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(eventEndSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(locationCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newAddressbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(invitationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(SubmitAppStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitAppEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(congressRadiobtn)
                    .addComponent(exhibitionRadiobtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeOrganizerbtn)
                    .addComponent(addOrganizerbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(addOrganizerByIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newEventbtn)
                    .addComponent(cancelbtn))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newEventbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEventbtnActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String name = nameTextField.getText();
        String dateBString = sdf.format(eventBeginningSpinner.getValue());
        String dateEString = sdf.format(eventEndSpinner.getValue());
        Location local = (Location) locationCombobox.getSelectedItem();

        String description = descriptionTextField.getText();
        String dateSubB = sdf.format(SubmitAppStart.getValue());
        String dateSubE = sdf.format(submitAppEnd.getValue());
        String invitesString = invitationTextField.getText();
        try {
            Date db = sdf.parse(dateBString);
            Date de = sdf.parse(dateEString);
            if (congressRadiobtn.isSelected()) {
                controller.getLocationList().getLocal(locationCombobox.getSelectedIndex()).setInUse(true);
                int invite = Integer.parseInt(invitesString);
                if (listOrganizers.size() > 1) {
                    Congress c = new Congress(name, description, db, de, local, invite);

                    c.setOrganizerList(listOrganizers);
                    listEvents.addEvent(c);
                    System.out.println("Congress");
                    JOptionPane.showMessageDialog(null, "Congress created with success!");
                    modelOrganizerListEvent.removeAllElements();
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Define at least 2 organizers for the event");
                }
            } else if (exhibitionRadiobtn.isSelected()) {
                int invite = Integer.parseInt(invitesString);
                if (listOrganizers.size() > 1) {
                    Exhibition e = new Exhibition(name, description, db, de, local, invite);

                    e.setOrganizerList(listOrganizers);
                    listEvents.addEvent(e);
                    System.out.println("Exhibition");
                    JOptionPane.showMessageDialog(null, "Exhibition created with success!");
                    modelOrganizerListEvent.removeAllElements();
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Define at least 2 organizers for the event");
                }

            } else if (!exhibitionRadiobtn.isSelected() && !congressRadiobtn.isSelected()) {
                JOptionPane.showMessageDialog(null, "Please choose the type of event");
            }

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Error inserting date");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error in number of invites field");
        }


    }//GEN-LAST:event_newEventbtnActionPerformed

    private void initObjects() {
        for (int i = 0; i < listUsers.size(); i++) {
            modelUsersList.addElement(listUsers.getUser(i));
        }
        for (int i = 0; i < locationList.size(); i++) {
            if (!locationList.getLocal(i).isInUse()) {
                locationCombobox.addItem(locationList.getLocal(i));
            }
        }
    }

    private void addOrganizerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrganizerbtnActionPerformed
        try {
            User u = modelUsersList.getElementAt(usersJList.getSelectedIndex());
            Organizer o = new Organizer(u);
            listOrganizers.addOrganizer(o);
            modelOrganizerListEvent.addElement(o);
            modelUsersList.removeElement(u);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "No user selected");
        }
    }//GEN-LAST:event_addOrganizerbtnActionPerformed

    private void removeOrganizerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeOrganizerbtnActionPerformed
        try {
            Organizer o = modelOrganizerListEvent.getElementAt(organizersList.getSelectedIndex());
            for (int i = 0; i < listUsers.size(); i++) {
                User u = listUsers.getUser(i);
                if (u.getUserName().equals(o.getOrganizer().getUserName())) {
                    modelUsersList.addElement(u);
                }
            }
            listOrganizers.removeOrganizer(o);
            modelOrganizerListEvent.removeElement(o);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "No organizer selected");
        }
    }//GEN-LAST:event_removeOrganizerbtnActionPerformed


    private void congressRadiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congressRadiobtnActionPerformed
        congressRadiobtn.setSelected(true);
        exhibitionRadiobtn.setSelected(false);
    }//GEN-LAST:event_congressRadiobtnActionPerformed

    private void locationComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationComboboxActionPerformed

    private void exhibitionRadiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exhibitionRadiobtnActionPerformed
        congressRadiobtn.setSelected(false);
        exhibitionRadiobtn.setSelected(true);
    }//GEN-LAST:event_exhibitionRadiobtnActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void addOrganizerByIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrganizerByIDTextFieldActionPerformed
        String userID = addOrganizerByIDTextField.getText();
        int cont = 0;
        if (!validateOrganizer(userID)) {
            for (int i = 0; i < listUsers.size(); i++) {
                User u = listUsers.getUser(i);
                if (u.getUserName().equals(userID) || u.getEmail().equals(userID)) {
                    Organizer o = new Organizer(u);
                    listOrganizers.addOrganizer(o);
                    modelOrganizerListEvent.addElement(o);
                    modelUsersList.removeElement(u);
                    cont++;
                }

            }
            if (cont == 0) {
                JOptionPane.showMessageDialog(null, "Given user doesn't exist");
            }
            cont = 0;
        } else {
            JOptionPane.showMessageDialog(null, "That user is already a Organizer of that event");
        }

        addOrganizerByIDTextField.setText("");
    }//GEN-LAST:event_addOrganizerByIDTextFieldActionPerformed
    public boolean validateOrganizer(String id) {
        for (int i = 0; i < listOrganizers.size(); i++) {
            String[] split = listOrganizers.getOrganizer(i).toString().split("; ");
            split[0] = split[0].split(":")[1];
            split[1] = split[1].split(":")[1];
            split[2] = split[2].split(":")[1];
            if (split[1].equals(id) || split[2].equals(id)) {
                return true;
            }
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CreateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CreateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CreateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CreateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CreateEvent().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SubmitAppStart;
    private javax.swing.JTextField addOrganizerByIDTextField;
    private javax.swing.JButton addOrganizerbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JRadioButton congressRadiobtn;
    private javax.swing.JTextArea descriptionTextField;
    private javax.swing.JSpinner eventBeginningSpinner;
    private javax.swing.JSpinner eventEndSpinner;
    private javax.swing.JRadioButton exhibitionRadiobtn;
    private javax.swing.JTextField invitationTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<Location> locationCombobox;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton newAddressbtn;
    private javax.swing.JButton newEventbtn;
    private javax.swing.JList<Organizer> organizersList;
    private javax.swing.JButton removeOrganizerbtn;
    private javax.swing.JSpinner submitAppEnd;
    private javax.swing.JList<User> usersJList;
    // End of variables declaration//GEN-END:variables
}
