/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lapr.project.controller.EventClassAcceptanceRateController;
import lapr.project.model.EventCenter;
import lapr.project.model.ShowEventAcceptanceRate;
import lapr.project.model.Statistics;
import lapr.project.model.Event;

/**
 *
 * @author MarioDias
 */
public class EventAcceptanceRateAboveFiftyUI extends javax.swing.JFrame {

    private static final long serialVersionUID = 1;
    private boolean option;
    private ShowEventAcceptanceRate eventAcceptanceRate;
    private EventClassAcceptanceRateController controller;
    private Statistics statistics;
    private Event event;

    /**
     * Creates new form EventAcceptanceRateAboveFiftyUI
     *
     * @param eventCenter
     * @param option
     * @param eventAcceptanceRate
     */
    public EventAcceptanceRateAboveFiftyUI(EventCenter eventCenter, boolean option) {
        initComponents();
        this.setVisible(true);
        controller = new EventClassAcceptanceRateController(eventCenter);
        this.option = option;
        if (option) {
            eventTwoCombobox.setVisible(false);
            populateEventCombobox();
        } else {
            populateEventCombobox();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventTextField = new javax.swing.JTextField();
        proporcionTextField = new javax.swing.JTextField();
        CritValueTextField = new javax.swing.JTextField();
        SigniValueTextField = new javax.swing.JTextField();
        ObsValueTextField = new javax.swing.JTextField();
        decisionTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        eventOneCombobox = new javax.swing.JComboBox<>();
        eventTwoCombobox = new javax.swing.JComboBox<>();
        selectBtn = new javax.swing.JButton();
        significanceTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        eventTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventTextFieldActionPerformed(evt);
            }
        });

        proporcionTextField.setEditable(false);
        proporcionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proporcionTextFieldActionPerformed(evt);
            }
        });

        CritValueTextField.setEditable(false);

        SigniValueTextField.setEditable(false);

        ObsValueTextField.setEditable(false);

        decisionTextField.setEditable(false);

        jLabel1.setText("Event");

        jLabel2.setText("Proporcion Accepted (n>30)");

        jLabel3.setText("Critical Value");

        jLabel4.setText("Significance Level (α%) ");

        jLabel5.setText("Observed Value Of test Statistic");

        jLabel6.setText("Decision");

        selectBtn.setText("Calculate");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        significanceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                significanceTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Significance Level:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(significanceTextField))
                    .addComponent(eventTwoCombobox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventOneCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ObsValueTextField)
                            .addComponent(SigniValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(CritValueTextField)
                            .addComponent(proporcionTextField)
                            .addComponent(decisionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(selectBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventTextField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eventOneCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventTwoCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(significanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proporcionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CritValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SigniValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ObsValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decisionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showValuesUnilateral() {
        double significance = Double.parseDouble(significanceTextField.getText());
        if (significance > 0 && significance < 1) {
            event = (Event) eventOneCombobox.getSelectedItem();
            eventAcceptanceRate = new ShowEventAcceptanceRate(event);
            int total = eventAcceptanceRate.getTotal();
            float acceptanceRate = (float) eventAcceptanceRate.getAcceptanceRate();
            if (option) {
                statistics = controller.setStatistics(significance, total, acceptanceRate);
                eventTextField.setText(event.getTitle());
                proporcionTextField.setText(String.format("%.3f %%", eventAcceptanceRate.getAcceptanceRate() * 100));
                CritValueTextField.setText(String.format("%.3f", statistics.getzCritical()));
                SigniValueTextField.setText(String.format("%.2f", significance));
                ObsValueTextField.setText(String.format("%.3f", statistics.getObsValue()));
                if (statistics.getObsValue() > statistics.getzCritical()) {
                    decisionTextField.setText("Yes");
                } else {
                    decisionTextField.setText("No");
                }
            } else {

            }
        } else {
            JOptionPane.showMessageDialog(null, "Please insert a valid significance value (Between 0 and 1)");
        }
    }

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        if (!significanceTextField.getText().isEmpty()) {
            showValuesUnilateral();
        } else {
            JOptionPane.showMessageDialog(null, "Please insert a valid significance value (Between 0 and 1)");
        }
    }//GEN-LAST:event_selectBtnActionPerformed

    private void proporcionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proporcionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proporcionTextFieldActionPerformed

    private void eventTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventTextFieldActionPerformed

    private void significanceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_significanceTextFieldActionPerformed
        showValuesUnilateral();
    }//GEN-LAST:event_significanceTextFieldActionPerformed

    private void populateEventCombobox() {
        for (int i = 0; i < controller.getEventRegistry().size(); i++) {
            eventOneCombobox.addItem(controller.getEventRegistry().getEvent(i));
        }
        if (!option) {
            for (int i = 0; i < controller.getEventRegistry().size(); i++) {
                eventTwoCombobox.addItem(controller.getEventRegistry().getEvent(i));
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CritValueTextField;
    private javax.swing.JTextField ObsValueTextField;
    private javax.swing.JTextField SigniValueTextField;
    private javax.swing.JTextField decisionTextField;
    private javax.swing.JComboBox<Event> eventOneCombobox;
    private javax.swing.JTextField eventTextField;
    private javax.swing.JComboBox<Event> eventTwoCombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField proporcionTextField;
    private javax.swing.JButton selectBtn;
    private javax.swing.JTextField significanceTextField;
    // End of variables declaration//GEN-END:variables
}
