package lapr.project.ui;

import javax.swing.JOptionPane;
import lapr.project.controller.EventClassAcceptanceRateController;
import lapr.project.model.EventCenter;
import lapr.project.model.ShowEventAcceptanceRate;
import lapr.project.model.Statistics;
import lapr.project.model.Event;

/**
 *
 * @author MarioDias
 */
public class EventAcceptanceRateAboveFiftyUI extends javax.swing.JFrame {

    private static final long serialVersionUID = 1;
    private boolean option;
    private ShowEventAcceptanceRate eventAcceptanceRateOne;
    private ShowEventAcceptanceRate eventAcceptanceRateTwo;
    private EventClassAcceptanceRateController controller;
    private Statistics statistics;
    private Event eventOne;
    private Event eventTwo;

    /**
     * Creates new form EventAcceptanceRateAboveFiftyUI
     *
     * @param eventCenter
     * @param option
     * @param eventAcceptanceRate
     */
    public EventAcceptanceRateAboveFiftyUI(EventCenter eventCenter, boolean option) {
        initComponents();
        this.setVisible(true);
        this.pack();
        controller = new EventClassAcceptanceRateController(eventCenter);
        this.option = option;
        if (option) {
            eventTwoCombobox.setVisible(false);
            proportionEventOneTextField.setVisible(false);
            labelProportionTextField.setVisible(false);
            labelProportionTwoTextField.setText("Proportion Accepted Event 1");
            populateEventCombobox();
        } else {
            populateEventCombobox();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventTextField = new javax.swing.JTextField();
        proportionEventTwoTextField = new javax.swing.JTextField();
        CritValueTextField = new javax.swing.JTextField();
        SigniValueTextField = new javax.swing.JTextField();
        ObsValueTextField = new javax.swing.JTextField();
        decisionTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        eventOneCombobox = new javax.swing.JComboBox<>();
        eventTwoCombobox = new javax.swing.JComboBox<>();
        selectBtn = new javax.swing.JButton();
        significanceTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        labelProportionTwoTextField = new javax.swing.JLabel();
        proportionEventOneTextField = new javax.swing.JTextField();
        labelProportionTextField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        eventTextField.setEditable(false);
        eventTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventTextFieldActionPerformed(evt);
            }
        });

        proportionEventTwoTextField.setEditable(false);
        proportionEventTwoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proportionEventTwoTextFieldActionPerformed(evt);
            }
        });

        CritValueTextField.setEditable(false);

        SigniValueTextField.setEditable(false);

        ObsValueTextField.setEditable(false);
        ObsValueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObsValueTextFieldActionPerformed(evt);
            }
        });

        decisionTextField.setEditable(false);

        jLabel1.setText("Event");

        jLabel3.setText("Critical Value");

        jLabel4.setText("Significance Level (α%) ");

        jLabel5.setText("Observed Value Of test Statistic");

        jLabel6.setText("Decision");

        selectBtn.setText("Calculate");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        significanceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                significanceTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Significance Level:");

        labelProportionTwoTextField.setText("Proportion Accepted Event 2");

        proportionEventOneTextField.setEditable(false);
        proportionEventOneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proportionEventOneTextFieldActionPerformed(evt);
            }
        });

        labelProportionTextField.setText("Proportion Accepted Event 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eventTwoCombobox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventOneCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelProportionTextField)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(labelProportionTwoTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CritValueTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(SigniValueTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ObsValueTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proportionEventTwoTextField)
                            .addComponent(proportionEventOneTextField)
                            .addComponent(decisionTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(significanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eventOneCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventTwoCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(significanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(selectBtn))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proportionEventOneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProportionTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proportionEventTwoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProportionTwoTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CritValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SigniValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ObsValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decisionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ShowValues() {
        double significance = Double.parseDouble(significanceTextField.getText());
        if (significance > 0 && significance < 1) {
            if (option) {
                eventOne = (Event) eventOneCombobox.getSelectedItem();
                eventAcceptanceRateOne = new ShowEventAcceptanceRate(eventOne);
                float acceptanceRate = (float) eventAcceptanceRateOne.getAcceptanceRate();
                int total = eventAcceptanceRateOne.getTotal();
                statistics = controller.setStatistics(significance, total, acceptanceRate);
                eventTextField.setText(eventOne.getTitle());
                proportionEventTwoTextField.setText(String.format("%.3f %%", eventAcceptanceRateOne.getAcceptanceRate() * 100));
                CritValueTextField.setText(String.format("%.3f", statistics.getzCritical()));
                SigniValueTextField.setText(String.format("%.2f", significance));
                ObsValueTextField.setText(String.format("%.3f", statistics.getObsValue()));
                if (statistics.getObsValue() > statistics.getzCritical()) {
                    decisionTextField.setText("Yes");
                } else {
                    decisionTextField.setText("No");
                }
            } else {
                eventOne = (Event) eventOneCombobox.getSelectedItem();
                eventTwo = (Event) eventTwoCombobox.getSelectedItem();
                eventAcceptanceRateOne = new ShowEventAcceptanceRate(eventOne);
                eventAcceptanceRateTwo = new ShowEventAcceptanceRate(eventTwo);
                int totalEventOne = eventAcceptanceRateOne.getTotal();
                float acceptanceRateOne = (float) eventAcceptanceRateOne.getAcceptanceRate();
                int totalEventTwo = eventAcceptanceRateTwo.getTotal();
                float acceptanceRateTwo = (float) eventAcceptanceRateTwo.getAcceptanceRate();
                statistics = controller.setStatisticsCompare(significance, totalEventOne, totalEventTwo, acceptanceRateOne, acceptanceRateTwo);
                eventTextField.setText(eventOne.getTitle() + " vs. " + eventTwo.getTitle());
                proportionEventOneTextField.setText(String.format("%.3f %%", eventAcceptanceRateOne.getAcceptanceRate() * 100));
                proportionEventTwoTextField.setText(String.format("%.3f %%", eventAcceptanceRateTwo.getAcceptanceRate() * 100));
                CritValueTextField.setText(String.format("%.3f", statistics.getzCritical()));
                SigniValueTextField.setText(String.format("%.2f", significance));
                ObsValueTextField.setText(String.format("%.3f", statistics.getObsValue()));
                if (statistics.getObsValue() > statistics.getzCritical()) {
                    decisionTextField.setText("Yes");
                } else {
                    decisionTextField.setText("No");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please insert a valid significance value (Between 0 and 1)");
        }
    }

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        if (!significanceTextField.getText().isEmpty()) {
            ShowValues();
        } else {
            JOptionPane.showMessageDialog(null, "Please insert a valid significance value (Between 0 and 1)");
        }
    }//GEN-LAST:event_selectBtnActionPerformed

    private void proportionEventTwoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proportionEventTwoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proportionEventTwoTextFieldActionPerformed

    private void eventTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventTextFieldActionPerformed

    private void significanceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_significanceTextFieldActionPerformed
        ShowValues();
    }//GEN-LAST:event_significanceTextFieldActionPerformed

    private void proportionEventOneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proportionEventOneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proportionEventOneTextFieldActionPerformed

    private void ObsValueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObsValueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObsValueTextFieldActionPerformed

    private void populateEventCombobox() {
        for (int i = 0; i < controller.getEventRegistry().size(); i++) {
            eventOneCombobox.addItem(controller.getEventRegistry().getEvent(i));
        }
        if (!option) {
            for (int i = 0; i < controller.getEventRegistry().size(); i++) {
                eventTwoCombobox.addItem(controller.getEventRegistry().getEvent(i));
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CritValueTextField;
    private javax.swing.JTextField ObsValueTextField;
    private javax.swing.JTextField SigniValueTextField;
    private javax.swing.JTextField decisionTextField;
    private javax.swing.JComboBox<Event> eventOneCombobox;
    private javax.swing.JTextField eventTextField;
    private javax.swing.JComboBox<Event> eventTwoCombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelProportionTextField;
    private javax.swing.JLabel labelProportionTwoTextField;
    private javax.swing.JTextField proportionEventOneTextField;
    private javax.swing.JTextField proportionEventTwoTextField;
    private javax.swing.JButton selectBtn;
    private javax.swing.JTextField significanceTextField;
    // End of variables declaration//GEN-END:variables
}
