package lapr.project.ui;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import lapr.project.model.EventCenter;
import lapr.project.model.EventEmployeeList;
import lapr.project.model.User;
import lapr.project.model.UserRegistry;

/**
 *
 * @author Miguel Santos <1161386@isep.ipp.pt>
 */
public class LoginUI extends javax.swing.JFrame {

    private static final long serialVersionUID = 1;
    private boolean loginStatus;
    private boolean userStatus = false;
    private boolean organizerStatus = false;
    private boolean eventEmployeeStatus = false;
    private boolean eventManagerStatus = false;
    private EventCenter eventCenter;
    private JLabel label;
    private String logedUser;

    private User user;

    /**
     * Creates new form LoginUI
     *
     * @param loginStatus
     * @param eventCenter
     * @param label
     * @param userStatus
     * @param organizerStatus
     * @param eventEmployeeStatus
     * @param eventManagerStatus
     * @param logedUser
     */
    public LoginUI(boolean loginStatus, EventCenter eventCenter, JLabel label, boolean userStatus, boolean organizerStatus, boolean eventEmployeeStatus, boolean eventManagerStatus) {
        this.loginStatus = loginStatus;
        this.eventCenter = eventCenter;
        this.label = label;
        this.userStatus = userStatus;
        this.organizerStatus = organizerStatus;
        this.eventEmployeeStatus = eventEmployeeStatus;
        this.eventManagerStatus = eventManagerStatus;
        this.userStatus = userStatus;
        this.organizerStatus = organizerStatus;
        this.eventEmployeeStatus = eventEmployeeStatus;
        this.eventManagerStatus = eventManagerStatus;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");

        jLabel1.setText("Username / Email:");

        jLabel2.setText("Password:");

        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idTextField)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginButton)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        loginConfirmation();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void loginConfirmation() {
        UserRegistry userRegistry = eventCenter.getUserRegistry();
        String loginName = idTextField.getText();
        String passwordInfo = new String(passwordField.getPassword());
        for (int i = 0; i < userRegistry.size(); i++) {
            System.out.println(i);
            if (userRegistry.getUser(i).getEmail().equals(loginName) || userRegistry.getUser(i).getUserName().equals(loginName)) {
                if (passwordInfo.equals(userRegistry.getUser(i).getPassword())) {
                    userStatus = true;
                    loginStatus = true;
                    this.user = userRegistry.getUser(i);                   
                    label.setText(user.getUserName());
                } else {
                    JOptionPane.showMessageDialog(null, "Wrong Password!");
                }
                if (loginStatus) {
                    this.organizerStatus = checkForOrganizerStatus(user);
                    this.eventEmployeeStatus = checkForEventEmployeeStatus(user);
                    this.eventManagerStatus = checkForEventManagerStatus(user);
                    break;
                }
            }
        }
        if (validateLoginStatus()) {
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "The user does not exist or invalid login info");
        }
        System.out.println("User:" + userStatus);
        System.out.println("Organizer:" + organizerStatus);
        System.out.println("Event Employee:" + eventEmployeeStatus);
        System.out.println("EventManager:" + eventManagerStatus);
    }

    private boolean validateLoginStatus() {
        if (isLoginStatus()) {
            userStatus = isUserStatus();
            organizerStatus = isOrganizerStatus();
            eventEmployeeStatus = isEventEmployeeStatus();
            eventManagerStatus = isEventManagerStatus();
            JOptionPane.showMessageDialog(null, "Success");
            return true;
        } else {
            return false;
        }
    }

    /**
     *
     * @return
     */
    public boolean isLoginStatus() {
        return loginStatus;
    }

    /**
     *
     * @return
     */
    public boolean isUserStatus() {
        return userStatus;
    }

    /**
     *
     * @return
     */
    public boolean isEventEmployeeStatus() {
        return eventEmployeeStatus;
    }

    /**
     *
     * @return
     */
    public boolean isEventManagerStatus() {
        return eventManagerStatus;
    }

    /**
     *
     * @return
     */
    public boolean isOrganizerStatus() {
        return organizerStatus;
    }

    /**
     *
     * @return
     */
    public User getUser() {
        return user;
    }

    /**
     *
     * @param user
     */
    public void setUser(User user) {
        this.user = user;
    }

    private boolean checkForEventManagerStatus(User user) {
        for (int i = 0; i < eventCenter.getEventManagerList().size(); i++) {
            if (eventCenter.getEventManagerList().getEventManager(i).getEmail().equals(user.getEmail()) || eventCenter.getEventManagerList().getEventManager(i).getUsername().equals(user.getUserName())) {
                return true;
            }
        }
        return false;
    }

    private boolean checkForEventEmployeeStatus(User user) {
        for (int i = 0; i < eventCenter.getEventRegistry().size(); i++) {
            EventEmployeeList employeeList = eventCenter.getEventRegistry().getEvent(i).getEventEmployeeList();
            for (int j = 0; j < employeeList.size(); j++) {
                if (employeeList.getEmployee(i).getEmail().equals(user.getEmail()) || employeeList.getEmployee(i).getUsername().equals(user.getUserName())) {
                    return true;
                }
            }

        }
        return false;
    }

    private boolean checkForOrganizerStatus(User user) {
        for (int i = 0; i < eventCenter.getOrganizersList().size(); i++) {
            if (eventCenter.getOrganizersList().getOrganizer(i).getEmail().equals(user.getEmail()) || eventCenter.getOrganizersList().getOrganizer(i).getUsername().equals(user.getUserName())) {
                return true;
            }
        }
        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables
}
